.TH "/Users/guanzhichao/course/计算机网络/protocol/include Directory Reference" 3 "Fri Nov 22 2019" "TCP/IP Ptotocol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/guanzhichao/course/计算机网络/protocol/include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBapi\&.h\fP"
.br
.RI "Library supporting api for users\&. "
.ti -1c
.RI "file \fBapiwrap\&.h\fP"
.br
.RI "Library for user to wrapping\&. "
.ti -1c
.RI "file \fBarp\&.h\fP"
.br
.RI "Library supporting sending and receiving ARP frame\&. "
.ti -1c
.RI "file \fBdevice\&.h\fP"
.br
.RI "Library supporting network device management\&. "
.ti -1c
.RI "file \fBether\&.h\fP"
.br
.RI "Library supporting a EtherFrame class\&. "
.ti -1c
.RI "file \fBip\&.h\fP"
.br
.RI "Library supporting sending/receiving IP packets encapsulated in an Ethernet II frame\&. "
.ti -1c
.RI "file \fBmassert\&.h\fP"
.br
.RI "Library supporting show message\&. "
.ti -1c
.RI "file \fBrouter\&.h\fP"
.br
.RI "Routing table and routing algorithm\&. "
.ti -1c
.RI "file \fBsdp\&.h\fP"
.br
.RI "Self Destruct Protocol: An Distance Vector Routing protocol\&. Read documents for more details\&. "
.ti -1c
.RI "file \fBsocket\&.h\fP"
.br
.RI "POSIX-compatible socket library supporting TCP protocol on IPv4\&. "
.ti -1c
.RI "file \fBsocketaddr\&.h\fP"
.br
.RI "Store a socket address\&. Providing \fCSocketAddr\fP and system \fCsockaddr\fP "
.ti -1c
.RI "file \fBtcp\&.h\fP"
.br
.RI "Main TCP functions and status\&. "
.ti -1c
.RI "file \fBtcpbuffer\&.h\fP"
.br
.RI "Buffer for TCP\&. Data received will be stored in \fC\fBBufferQueue\fP\fP\&. "
.ti -1c
.RI "file \fBtcpsegment\&.h\fP"
.br
.RI "TCP flags, TCP segment and TCP item (stored IP address)\&. "
.ti -1c
.RI "file \fBtcpseq\&.h\fP"
.br
.RI "TCP sequence number\&. "
.ti -1c
.RI "file \fBtcpstate\&.h\fP"
.br
.RI "State of TCP(Socket) "
.ti -1c
.RI "file \fBtype\&.h\fP"
.br
.RI "Define some types and constant will be used\&. "
.in -1c
