.TH "Ether" 3 "Fri Nov 22 2019" "TCP/IP Ptotocol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ether
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEtherFrame\fP"
.br
.RI "Store a Ethernet frame\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const u_char \fBbroadcastMacAddr\fP [6] = {255, 255, 255, 255, 255, 255}"
.br
.ti -1c
.RI "const u_char \fBzeroMacAddr\fP [6] = {0, 0, 0, 0, 0, 0}"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const u_char Ether::broadcastMacAddr = {255, 255, 255, 255, 255, 255}"

.SS "const u_char Ether::zeroMacAddr = {0, 0, 0, 0, 0, 0}"

.SH "Author"
.PP 
Generated automatically by Doxygen for TCP/IP Ptotocol from the source code\&.
