.TH "MAC::MacAddr" 3 "Fri Nov 22 2019" "TCP/IP Ptotocol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MAC::MacAddr \- A class storing a \fBMAC\fP address\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ether\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMacAddr\fP ()"
.br
.ti -1c
.RI "\fBMacAddr\fP (const u_char *_mac)"
.br
.ti -1c
.RI "const \fBMacAddr\fP & \fBoperator=\fP (const \fBMacAddr\fP &m)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "u_char \fBaddr\fP [6]"
.br
.in -1c
.SH "Detailed Description"
.PP 
A class storing a \fBMAC\fP address\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "MAC::MacAddr::MacAddr ()\fC [inline]\fP"

.SS "MAC::MacAddr::MacAddr (const u_char * _mac)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const \fBMacAddr\fP & MAC::MacAddr::operator= (const \fBMacAddr\fP & m)"

.SH "Member Data Documentation"
.PP 
.SS "u_char MAC::MacAddr::addr[6]"


.SH "Author"
.PP 
Generated automatically by Doxygen for TCP/IP Ptotocol from the source code\&.
