.TH "/Users/guanzhichao/course/计算机网络/protocol/include/tcpbuffer.h" 3 "Fri Nov 22 2019" "TCP/IP Ptotocol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/guanzhichao/course/计算机网络/protocol/include/tcpbuffer.h \- Buffer for TCP\&. Data received will be stored in \fC\fBBufferQueue\fP\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <deque>\fP
.br
\fC#include 'massert\&.h'\fP
.br
\fC#include 'type\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBufferQueue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Buffer for TCP\&. Data received will be stored in \fC\fBBufferQueue\fP\fP\&. 


.PP
\fBAuthor\fP
.RS 4
guanzhichao (vbcpascal@gmail.com) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2019-11-15 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TCP/IP Ptotocol from the source code\&.
