.TH "/Users/guanzhichao/course/计算机网络/protocol/include/tcpstate.h" 3 "Fri Nov 22 2019" "TCP/IP Ptotocol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/guanzhichao/course/计算机网络/protocol/include/tcpstate.h \- State of TCP(Socket)  

.SH SYNOPSIS
.br
.PP
\fC#include 'massert\&.h'\fP
.br
\fC#include 'type\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBTcp\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTCP_STATE_SET\fP"
.br
.ti -1c
.RI "#define \fBX\fP(STATENAME)   STATENAME,"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTcp::TcpState\fP : int { \fBTcp::TcpState::X\fP, \fBTcp::TcpState::TCP_STATE_SET\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBTcp::stateToStr\fP (TcpState st)"
.br
.in -1c
.SH "Detailed Description"
.PP 
State of TCP(Socket) 


.PP
\fBAuthor\fP
.RS 4
guanzhichao (vbcpascal@gmail.com) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2019-11-17 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define TCP_STATE_SET"
\fBValue:\fP
.PP
.nf
X(INVAL)            \
  X(CLOSED)           \
  X(LISTEN)           \
  X(SYN_SENT)         \
  X(SYN_RECEIVED)     \
  X(ESTABLISHED)      \
  X(CLOSE_WAIT)       \
  X(FIN_WAIT_1)       \
  X(CLOSING)          \
  X(LAST_ACK)         \
  X(FIN_WAIT_2)       \
  X(TIMED_WAIT)
.fi
.SS "#define X(STATENAME)   STATENAME,"

.SH "Author"
.PP 
Generated automatically by Doxygen for TCP/IP Ptotocol from the source code\&.
