.TH "/Users/guanzhichao/course/计算机网络/protocol/tests/testSendFrame.cpp" 3 "Fri Nov 22 2019" "TCP/IP Ptotocol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/guanzhichao/course/计算机网络/protocol/tests/testSendFrame.cpp \- Test: open one device and send 100 frames to destination \fBMAC\fP address\&. It is necessary to set device with the same program on the dst host\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <csignal>\fP
.br
\fC#include 'api\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBdefaultCallback\fP (const void *buf, int len, \fBDeviceId\fP id)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBcount\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Test: open one device and send 100 frames to destination \fBMAC\fP address\&. It is necessary to set device with the same program on the dst host\&. 


.PP
\fBAuthor\fP
.RS 4
guanzhichao (vbcpascal@gmail.com) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2019-11-19 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int defaultCallback (const void * buf, int len, \fBDeviceId\fP id)"

.SS "int main ()"

.SH "Variable Documentation"
.PP 
.SS "int count = 0"

.SH "Author"
.PP 
Generated automatically by Doxygen for TCP/IP Ptotocol from the source code\&.
