.TH "/Users/guanzhichao/course/计算机网络/protocol/tests/testDeviceManager.cpp" 3 "Fri Nov 22 2019" "TCP/IP Ptotocol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/guanzhichao/course/计算机网络/protocol/tests/testDeviceManager.cpp \- Test: open all devices and begin listening on them\&. An warning will be shown when trying to add a device opened\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'api\&.h'\fP
.br
\fC#include 'device\&.h'\fP
.br
\fC#include 'ether\&.h'\fP
.br
\fC#include 'type\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmyCallback\fP (const void *buf, int len, \fBDeviceId\fP id)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Detailed Description"
.PP 
Test: open all devices and begin listening on them\&. An warning will be shown when trying to add a device opened\&. 


.PP
\fBAuthor\fP
.RS 4
guanzhichao (vbcpascal@gmail.com) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2019-10-02 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SS "int myCallback (const void * buf, int len, \fBDeviceId\fP id)"

.SH "Author"
.PP 
Generated automatically by Doxygen for TCP/IP Ptotocol from the source code\&.
