#!/bin/bash

SCRIPT_DIR="$(dirname ${BASH_SOURCE[0]})"
pushd "${VNET_EXAMPLE_DIR}"

./vecho "\e[1;34m$0 $*\e[0m"
./vdo sysctl -q net.ipv4.ip_forward=1
./vdo sysctl -q net.ipv4.conf.all.forwarding=1

popd