#!/bin/bash

SCRIPT_DIR="$(dirname ${BASH_SOURCE[0]})"
pushd "${VNET_EXAMPLE_DIR}"

./vecho "\e[1;34m$0 $*\e[0m"
if [[ "s${2: -3:3}" != "sns0" ]]; 
then
    ./vdo ip link set $1 netns $2
else 
    ./vdo ip link set $1 netns $$
fi

popd